import os
from pathlib import Path

from dotenv import load_dotenv

# Path to .env file
env_path = Path(__file__).parent / ".env"
_env_loaded = False


def _ensure_env_loaded() -> None:
    """Load environment variables from .env file if not already loaded.

    Only loads if the .env file exists. Should be called before accessing
    any environment variables.
    """
    global _env_loaded
    if not _env_loaded and env_path.exists():
        load_dotenv(dotenv_path=env_path, override=True)
        _env_loaded = True


def exists() -> bool:
    """Check if .env configuration file exists.

    Returns:
        True if .env file exists, False otherwise.
    """
    return env_path.exists()


def get(key: str, default: str | None = None) -> str | None:
    """Get configuration value from environment.

    Args:
        key: Environment variable name.
        default: Default value if key not found.

    Returns:
        Configuration value or default.
    """
    _ensure_env_loaded()
    return os.getenv(key, default)


def get_required(key: str) -> str:
    """Get required configuration value from environment.

    Args:
        key: Environment variable name.

    Returns:
        Configuration value.

    Raises:
        ValueError: If required key is not found.
    """
    _ensure_env_loaded()
    value = os.getenv(key)
    if value is None:
        raise ValueError(f"Required environment variable '{key}' not found")
    return value


def setup_interactive() -> None:
    """Interactive setup wizard for first-time configuration.

    Prompts user for Discord bot token, channel ID, and schedule hour,
    then creates the .env file.
    """
    print("\n=== Benfica Discord Bot - First Time Setup ===\n")
    print("This wizard will help you configure the bot.\n")

    # Get Discord bot token
    print("1. Discord Bot Token")
    print(
        "   Get your token from: "
        "https://discord.com/developers/applications"
    )
    token = input("   Enter your Discord bot token: ").strip()
    while not token:
        print("   Error: Token cannot be empty!")
        token = input("   Enter your Discord bot token: ").strip()

    # Get channel ID
    print("\n2. Channel ID")
    print("   Enable Developer Mode in Discord, right-click your channel,")
    print("   and select 'Copy Channel ID'")
    channel_id = input("   Enter the Discord channel ID: ").strip()
    while not channel_id or not channel_id.isdigit():
        print("   Error: Channel ID must be a number!")
        channel_id = input("   Enter the Discord channel ID: ").strip()

    # Get schedule hour
    print("\n3. Daily Schedule")
    print("   What hour (0-23) should the bot post newspaper covers daily?")
    hour = input("   Enter hour (default: 8): ").strip() or "8"
    while not hour.isdigit() or not (0 <= int(hour) <= 23):
        print("   Error: Hour must be a number between 0 and 23!")
        hour = input("   Enter hour (default: 8): ").strip() or "8"

    # Create .env file
    env_content = f"""# Discord Bot Configuration
# Generated by setup wizard

# Discord bot token from https://discord.com/developers/applications
DISCORD_TOKEN={token}

# Discord channel ID where the bot will post
DISCORD_CHANNEL_ID={channel_id}

# Hour (0-23) when daily newspaper covers should be posted
SCHEDULE_HOUR={hour}
"""

    with open(env_path, "w") as f:
        f.write(env_content)

    # Load the newly created .env file
    global _env_loaded
    _env_loaded = False
    _ensure_env_loaded()

    print(f"\n✓ Configuration saved to {env_path}")
    print("\nYou can now start the bot with: uv run python bot.py")
    print("Or manually edit .env if you need to change settings.\n")
